/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package babyKun.scenes;

import static babyKun.scenes.Basket.listModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Bag extends javax.swing.JPanel {

    /**
     * Define instances that in the bag.
     */
    mainJFrame mj;
    static String kunName;
    static ArrayList<Object> purchased = new ArrayList<Object>();
    static int numberOfHP;
    static int numberOfMP;
    //number of skill books
    int numberOfJ;
    int numberOfS;
    int numberOfR;
    int numberOfB;

    /**
     * Constructor for the bag
     *
     * @param frame main class mainJFrame to ensure all the panels are on one
     * JFrame.
     */
    public Bag(mainJFrame frame) {
        this.mj = frame;
        initComponents();
        itemAdded();
        unlockItem();
    }

    /**
     * This method is to calculate the number of items that user purchased from
     * shop.
     */
    public void itemAdded() {

        for (int i = 0; i < purchased.size(); i++) {

            if (purchased.get(i).equals("@ $" + Shop.healthAmounts + "/1* " + "Health Potion")) {
                numberOfHP += 1;
            }
            if (purchased.get(i).equals("@ $" + Shop.manaAmounts + "/1* " + "Mana Potion")) {
                numberOfMP += 1;
            }
            if (purchased.get(i).equals("@ $" + Shop.singAmounts + "/1* " + "Sing skill book")) {
                numberOfS += 1;
            }
            if (purchased.get(i).equals("@ $" + Shop.jumpAmounts + "/1* " + "Jump skill book")) {
                numberOfJ += 1;
            }
            if (purchased.get(i).equals("@ $" + Shop.rapAmounts + "/1* " + "Rap skill book")) {
                numberOfR += 1;
            }
            if (purchased.get(i).equals("@ $" + Shop.basketBallAmounts + "/1* " + "Basketball skill book")) {
                numberOfB += 1;
            }

        }
        //clear the purchase array, make sure it will not append.
        purchased.clear();

        //invoke the method to update Jlabels.
        updatelabelAmount();

    }

    /**
     * Method to bulk set the text for all the products based on new number of
     * items purchased.
     */
    public void updatelabelAmount() {

        hpNumberLabel.setText(Integer.toString(numberOfHP));
        mpNumberLabel.setText(Integer.toString(numberOfMP));
        sNumberLabel.setText(Integer.toString(numberOfS));
        jNumberLabel.setText(Integer.toString(numberOfJ));
        rNumberLabel.setText(Integer.toString(numberOfR));
        bNumberLabel.setText(Integer.toString(numberOfB));

    }

    /**
     * Method to unlock item if the number of which is above 0.
     */
    public void unlockItem() {

        if (numberOfHP > 0) {
            hpButton.setEnabled(true);
        }
        if (numberOfMP > 0) {
            mpButton.setEnabled(true);
        }
        if (numberOfS > 0) {
            sButton.setEnabled(true);
        }
        if (numberOfJ > 0) {
            jButton.setEnabled(true);
        }
        if (numberOfR > 0) {
            rButton.setEnabled(true);
        }
        if (numberOfB > 0) {
            bButton.setEnabled(true);
        }
    }

    /**
     * Method to get the remained health.
     *
     * @param total total health
     * @param defence kun's defence
     * @param attack enemy's attack
     * @return difference- remained health
     */
    public int remainedHealth(int total, int defence, int attack) {

        int damage = (attack - defence);
        if (damage < 0) {
            damage = 1;
        }
        int currentHealth = total - damage;
        if (currentHealth < 0) {
            currentHealth = 0;
        }
        return currentHealth;
    }

    /**
     * method to check if kun needs a potion.
     *
     * @param total total health
     * @param remained remained health
     * @param healthAmount health amount per potion
     * @return
     */
    public boolean ifDrinkHealthPotion(int total, int remained, int healthAmount) {
        boolean status = true;

        if ((total - remained) > healthAmount) {
            status = false;
        }
        return status;
    }

    /**
     * remove current panel to fight panel.
     */
    public void goToFight() {

        JPanel fight = new Fight(this.mj);
        this.mj.getContentPane().removeAll();
        this.mj.add(fight);
        this.mj.revalidate();
        this.mj.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        line7 = new javax.swing.JLabel();
        singLabel = new javax.swing.JLabel();
        sNumberLabel = new javax.swing.JLabel();
        sButton = new javax.swing.JButton();
        jPanel35 = new javax.swing.JPanel();
        line8 = new javax.swing.JLabel();
        basketBallLabel = new javax.swing.JLabel();
        bNumberLabel = new javax.swing.JLabel();
        bButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        line5 = new javax.swing.JLabel();
        rapLabel = new javax.swing.JLabel();
        rNumberLabel = new javax.swing.JLabel();
        rButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        line4 = new javax.swing.JLabel();
        jumpLabel = new javax.swing.JLabel();
        jNumberLabel = new javax.swing.JLabel();
        jButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        line = new javax.swing.JLabel();
        healthLabel = new javax.swing.JLabel();
        hpNumberLabel = new javax.swing.JLabel();
        hpButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        line6 = new javax.swing.JLabel();
        manaLabel = new javax.swing.JLabel();
        mpNumberLabel = new javax.swing.JLabel();
        mpButton = new javax.swing.JButton();
        bagLabel = new javax.swing.JLabel();
        backToFight = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        jPanel1.setLayout(null);

        jPanel7.setLayout(null);

        line7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/line.png"))); // NOI18N
        line7.setText("jLabel1");
        jPanel7.add(line7);
        line7.setBounds(0, 0, 700, 3);

        singLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        singLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/microphoneIcon.png"))); // NOI18N
        singLabel.setText("Sing Skill Book");
        jPanel7.add(singLabel);
        singLabel.setBounds(40, 0, 180, 50);

        sNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sNumberLabel.setText("0");
        jPanel7.add(sNumberLabel);
        sNumberLabel.setBounds(260, 20, 50, 16);

        sButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sButton.setText("Use");
        sButton.setEnabled(false);
        sButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButtonActionPerformed(evt);
            }
        });
        jPanel7.add(sButton);
        sButton.setBounds(380, 10, 75, 29);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 140, 470, 50);

        jPanel35.setLayout(null);

        line8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/line.png"))); // NOI18N
        line8.setText("jLabel1");
        jPanel35.add(line8);
        line8.setBounds(0, 0, 700, 3);

        basketBallLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        basketBallLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/basketballIcon.png"))); // NOI18N
        basketBallLabel.setText("Basketball Skill Book");
        jPanel35.add(basketBallLabel);
        basketBallLabel.setBounds(30, 0, 240, 50);

        bNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bNumberLabel.setText("0");
        jPanel35.add(bNumberLabel);
        bNumberLabel.setBounds(260, 20, 50, 16);

        bButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bButton.setText("Use");
        bButton.setEnabled(false);
        bButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bButtonActionPerformed(evt);
            }
        });
        jPanel35.add(bButton);
        bButton.setBounds(380, 10, 75, 29);

        jPanel1.add(jPanel35);
        jPanel35.setBounds(0, 290, 460, 50);

        jPanel5.setLayout(null);

        line5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/line.png"))); // NOI18N
        line5.setText("jLabel1");
        jPanel5.add(line5);
        line5.setBounds(0, 0, 700, 3);

        rapLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rapLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/rapperIcon.png"))); // NOI18N
        rapLabel.setText("Rap Skill Book");
        rapLabel.setToolTipText("");
        jPanel5.add(rapLabel);
        rapLabel.setBounds(40, 0, 170, 50);

        rNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rNumberLabel.setText("0");
        jPanel5.add(rNumberLabel);
        rNumberLabel.setBounds(260, 20, 50, 16);

        rButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rButton.setText("Use");
        rButton.setEnabled(false);
        rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonActionPerformed(evt);
            }
        });
        jPanel5.add(rButton);
        rButton.setBounds(380, 10, 75, 29);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 240, 470, 50);

        jPanel4.setLayout(null);

        line4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/line.png"))); // NOI18N
        line4.setText("jLabel1");
        jPanel4.add(line4);
        line4.setBounds(0, 0, 700, 3);

        jumpLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jumpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/shoeIcon.png"))); // NOI18N
        jumpLabel.setText("Jump Skill Book");
        jumpLabel.setToolTipText("");
        jPanel4.add(jumpLabel);
        jumpLabel.setBounds(40, 0, 170, 50);

        jNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jNumberLabel.setText("0");
        jPanel4.add(jNumberLabel);
        jNumberLabel.setBounds(260, 20, 50, 16);

        jButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton.setText("Use");
        jButton.setEnabled(false);
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        jPanel4.add(jButton);
        jButton.setBounds(380, 10, 75, 29);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 190, 470, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Item");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Number of Item");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(jLabel3)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 20, 460, 20);

        jPanel3.setLayout(null);

        line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/line.png"))); // NOI18N
        line.setText("jLabel1");
        jPanel3.add(line);
        line.setBounds(0, 0, 700, 3);

        healthLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        healthLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/health_potion_icon.png"))); // NOI18N
        healthLabel.setText("Health Potion");
        jPanel3.add(healthLabel);
        healthLabel.setBounds(40, 0, 134, 50);

        hpNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        hpNumberLabel.setText("0");
        jPanel3.add(hpNumberLabel);
        hpNumberLabel.setBounds(260, 20, 50, 16);

        hpButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        hpButton.setText("Use");
        hpButton.setEnabled(false);
        hpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpButtonActionPerformed(evt);
            }
        });
        jPanel3.add(hpButton);
        hpButton.setBounds(380, 10, 75, 29);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 40, 470, 50);

        jPanel6.setLayout(null);

        line6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/line.png"))); // NOI18N
        line6.setText("jLabel1");
        jPanel6.add(line6);
        line6.setBounds(0, 0, 700, 3);

        manaLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        manaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/manapotion_icon.png"))); // NOI18N
        manaLabel.setText("Mana Potion");
        jPanel6.add(manaLabel);
        manaLabel.setBounds(40, 0, 128, 50);

        mpNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mpNumberLabel.setText("0");
        jPanel6.add(mpNumberLabel);
        mpNumberLabel.setBounds(260, 20, 50, 16);

        mpButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mpButton.setText("Use");
        mpButton.setEnabled(false);
        mpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpButtonActionPerformed(evt);
            }
        });
        jPanel6.add(mpButton);
        mpButton.setBounds(380, 10, 75, 29);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 90, 470, 50);

        add(jPanel1);
        jPanel1.setBounds(160, 80, 460, 340);

        bagLabel.setBackground(new java.awt.Color(0, 0, 0));
        bagLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/bag.png"))); // NOI18N
        bagLabel.setToolTipText("");
        add(bagLabel);
        bagLabel.setBounds(0, 0, 400, 500);

        backToFight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backToFight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/castle.png"))); // NOI18N
        backToFight.setText("back");
        backToFight.setActionCommand("Back");
        backToFight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToFightActionPerformed(evt);
            }
        });
        add(backToFight);
        backToFight.setBounds(580, 450, 120, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void backToFightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToFightActionPerformed
        goToFight();
    }//GEN-LAST:event_backToFightActionPerformed

    private void hpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpButtonActionPerformed

        // check if Kun needs a health potion, if yes, increase Kun's current health.
        if ((Fight.kun.getHealth() - Fight.kunCurrentHealth) >= 100) {

            Kun.currentHealth += 100;

            numberOfHP--;
            //update all numbers of items in the bag.
            updatelabelAmount();
            JOptionPane.showMessageDialog(null, kunName + " has been healed for 100HP");

        } else {
            JOptionPane.showMessageDialog(null, kunName + " is pretty healthy now");
        }

        if (numberOfHP <= 0) {
            //if the number of item is equal to 0, user cannot click.
            hpButton.setEnabled(false);
        }
    }//GEN-LAST:event_hpButtonActionPerformed

    private void mpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpButtonActionPerformed
        // check if Kun needs a mana potion, if yes, increase Kun's current mana.
        if ((Fight.kun.getMana() - Fight.kunCurrentMana) >= 50) {

            Kun.currentMana += 50;

            numberOfMP--;
            updatelabelAmount();
            //update all numbers of items in the bag.
            JOptionPane.showMessageDialog(null, kunName + " has been healed for 50MP");
        } else {
            JOptionPane.showMessageDialog(null, kunName + " is pretty healthy now");
        }

        if (numberOfMP <= 0) {
            //if the number of item is equal to 0, user cannot click.
            mpButton.setEnabled(false);

        }
    }//GEN-LAST:event_mpButtonActionPerformed

    private void sButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButtonActionPerformed
        numberOfS--;
        //update all numbers of items in the bag.
        updatelabelAmount();
        if (numberOfS <= 0) {
            sButton.setEnabled(false);
        }
    }//GEN-LAST:event_sButtonActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        numberOfJ--;
        //update all numbers of items in the bag.
        updatelabelAmount();
        if (numberOfJ <= 0) {
            jButton.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonActionPerformed

    private void rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonActionPerformed
        numberOfR--;
        //update all numbers of items in the bag.
        updatelabelAmount();
        if (numberOfR <= 0) {
            rButton.setEnabled(false);
        }
    }//GEN-LAST:event_rButtonActionPerformed

    private void bButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bButtonActionPerformed
        numberOfB--;
        //update all numbers of items in the bag.
        updatelabelAmount();
        if (numberOfB <= 0) {
            bButton.setEnabled(false);
        }
    }//GEN-LAST:event_bButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bButton;
    private javax.swing.JLabel bNumberLabel;
    private javax.swing.JButton backToFight;
    private javax.swing.JLabel bagLabel;
    private javax.swing.JLabel basketBallLabel;
    private javax.swing.JLabel healthLabel;
    private javax.swing.JButton hpButton;
    private javax.swing.JLabel hpNumberLabel;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jNumberLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jumpLabel;
    private javax.swing.JLabel line;
    private javax.swing.JLabel line4;
    private javax.swing.JLabel line5;
    private javax.swing.JLabel line6;
    private javax.swing.JLabel line7;
    private javax.swing.JLabel line8;
    private javax.swing.JLabel manaLabel;
    private javax.swing.JButton mpButton;
    private javax.swing.JLabel mpNumberLabel;
    private javax.swing.JButton rButton;
    private javax.swing.JLabel rNumberLabel;
    private javax.swing.JLabel rapLabel;
    private javax.swing.JButton sButton;
    private javax.swing.JLabel sNumberLabel;
    private javax.swing.JLabel singLabel;
    // End of variables declaration//GEN-END:variables
}
