/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package babyKun.scenes;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jack
 */
public class Basket extends javax.swing.JPanel {

    /**
     * Define instances. Static listmodel will be initilized in the shop class.
     */
    static DefaultListModel listModel = new DefaultListModel();
    mainJFrame mj;
    static int balance = 500;

    /**
     * Constructor for Basket
     *
     * @param mj frame main class mainJFrame to ensure all the panels are on one
     * JFrame.
     */
    public Basket(mainJFrame mj) {
        this.mj = mj;
        initComponents();
        goldText.setText("Current Gold: " + balance);
        list.setModel(listModel);
        text.setText("Total: $" + totalAmount() + "\ninclusive GST\n\nThank you!");

    }

    /**
     * Method to get a total amount that user bought in a string format.
     *
     * @return total amount that user bought in a string format.
     */
    public String totalAmount() {

        int totalAmount = 0;
        for (int i = 0; i < listModel.getSize(); i++) {
            //unit prices are static, so we can just use them here.
            if (listModel.getElementAt(i).equals("@ $" + Shop.healthAmounts + "/1* " + "Health Potion")) {
                totalAmount += Shop.healthAmounts;
            }
            if (listModel.getElementAt(i).equals("@ $" + Shop.manaAmounts + "/1* " + "Mana Potion")) {
                totalAmount += Shop.manaAmounts;
            }
            if (listModel.getElementAt(i).equals("@ $" + Shop.singAmounts + "/1* " + "Sing skill book")) {
                totalAmount += Shop.singAmounts;
            }
            if (listModel.getElementAt(i).equals("@ $" + Shop.jumpAmounts + "/1* " + "Jump skill book")) {
                totalAmount += Shop.jumpAmounts;
            }
            if (listModel.getElementAt(i).equals("@ $" + Shop.rapAmounts + "/1* " + "Rap skill book")) {
                totalAmount += Shop.rapAmounts;
            }
            if (listModel.getElementAt(i).equals("@ $" + Shop.basketBallAmounts + "/1* " + "Basketball skill book")) {
                totalAmount += Shop.basketBallAmounts;
            }

        }
        return Integer.toString(totalAmount);
    }

    /**
     * clear current JFrame, and load Shop panel.
     */
    public void goToShop() {

        JPanel shop = new Shop(this.mj);
        this.mj.getContentPane().removeAll();
        this.mj.add(shop);
        this.mj.revalidate();
        this.mj.repaint();
    }

    /**
     * Method to return the total amount of products purchased
     *
     * @param arr list of products
     * @return total prices
     */
    public int totalAmount(ArrayList<Integer> arr) {
        int amount = 0;

        if (arr == null) {
            System.out.println("You have not made a shopping!");
        } else {
            for (Integer o : arr) {
                amount += o;
            }
        }

        return amount;
    }

    /**
     * Method to get non duplicate arraylist.
     *
     * @param arr list of products
     * @return non duplicate arraylist.
     */
    public ArrayList<Integer> clearDuplicate(ArrayList<Integer> arr) {

        ArrayList<Integer> newList = new ArrayList<Integer>();

        for (int dup : arr) {

            if (!newList.contains(dup)) {
                newList.add(dup);
            }
        }

        return newList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shopLabel = new javax.swing.JLabel();
        Checkout = new javax.swing.JButton();
        backToShop = new javax.swing.JButton();
        goldText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        lineLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        backgroundLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        shopLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/shop.png"))); // NOI18N
        add(shopLabel);
        shopLabel.setBounds(560, 50, 100, 100);

        Checkout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/moneybag.png"))); // NOI18N
        Checkout.setText("CheckOut");
        Checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutActionPerformed(evt);
            }
        });
        add(Checkout);
        Checkout.setBounds(560, 390, 140, 40);

        backToShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/castle.png"))); // NOI18N
        backToShop.setText("Back");
        backToShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToShopActionPerformed(evt);
            }
        });
        add(backToShop);
        backToShop.setBounds(560, 440, 140, 40);

        goldText.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        goldText.setForeground(new java.awt.Color(255, 153, 0));
        add(goldText);
        goldText.setBounds(520, 160, 180, 40);

        jPanel1.setLayout(null);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/drag.png"))); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton);
        deleteButton.setBounds(0, 400, 170, 40);

        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/portion.png"))); // NOI18N
        clearButton.setText("Clear All");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearButton);
        clearButton.setBounds(170, 400, 170, 40);

        lineLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/line.png"))); // NOI18N
        jPanel1.add(lineLabel);
        lineLabel.setBounds(0, 280, 340, 10);

        jScrollPane1.setViewportView(list);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 340, 280);

        text.setEditable(false);
        text.setColumns(20);
        text.setRows(5);
        jScrollPane2.setViewportView(text);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 290, 340, 110);

        add(jPanel1);
        jPanel1.setBounds(110, 40, 340, 440);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/background.png"))); // NOI18N
        add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 710, 541);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            //index in the Jlist.
            int index = list.getSelectedIndex();
            //remove the selected row in the JList.
            listModel.removeElementAt(index);
            list.setModel(listModel);
            text.setText("Total: $" + totalAmount() + "\ninclusive GST\n\nThank you!");

        } catch (Exception exp) {

        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        //clear all the elements in Jlist.
        listModel.clear();
        list.setModel(listModel);
        text.setText("Total: $" + totalAmount() + "\ninclusive GST\n\nThank you!");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void backToShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToShopActionPerformed
        goToShop();
    }//GEN-LAST:event_backToShopActionPerformed

    private void CheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutActionPerformed

        //If balance is higher than total amount, transaction can be done. 
        if (balance >= Integer.parseInt(totalAmount())) {
            balance -= Integer.parseInt(totalAmount());
            goldText.setText("Current Gold: " + balance);
            JOptionPane.showMessageDialog(null, "Added to your bag!");
            //pass all the products purchased into Bag.
            for (int i = 0; i < listModel.getSize(); i++) {
                Bag.purchased.add(listModel.getElementAt(i));
            }

            listModel.clear();
            list.setModel(listModel);
            text.setText("Total: $" + totalAmount() + "\ninclusive GST\n\nThank you!");

        } else {
            JOptionPane.showMessageDialog(null, "Not sufficent fund, earn more!");
        }
    }//GEN-LAST:event_CheckoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Checkout;
    private javax.swing.JButton backToShop;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField goldText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lineLabel;
    private javax.swing.JList<String> list;
    private javax.swing.JLabel shopLabel;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
