/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package babyKun.scenes;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Action;
import javax.swing.Timer;

/**
 *
 * @author Jack
 */
public class FinalScene extends javax.swing.JPanel {

    /**
     * Define instances
     */
    mainJFrame mj;
    Timer tm;
    int locationX;
    int locationY;
    int velx = 15;
    int vely = 15;

    /**
     * Constructor for finalScene
     *
     * @param frame frame main class mainJFrame to ensure all the panels are on
     * one
     */
    public FinalScene(mainJFrame frame) {
        this.mj = frame;
        initComponents();
        movingWord();
    }

    /**
     * ActionListener for bouncing ball.
     */
    public void movingWord() {

        locationX = flyingLabel.getLocation().x;
        locationY = flyingLabel.getLocation().y;

        ActionListener flying = new ActionListener() {

            public void actionPerformed(ActionEvent e) {

                if (locationY >= 390) {
                    vely = -15;

                }
                if (locationX >= 560) {
                    velx = -15;

                }

                if (locationY <= 0) {
                    vely = 15;

                }
                if (locationX <= 0) {
                    velx = 15;

                }
                locationX += velx;
                locationY += vely;
                flyingLabel.setLocation(locationX, locationY);

            }
        };
        //delay every 70 ms.
        tm = new Timer(70, flying);
        tm.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flyingLabel = new javax.swing.JLabel();
        lastLabel = new javax.swing.JLabel();
        backToMainButton = new javax.swing.JButton();
        lastLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        flyingLabel.setForeground(new java.awt.Color(255, 255, 255));
        flyingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/basketballBig.png"))); // NOI18N
        add(flyingLabel);
        flyingLabel.setBounds(10, 370, 140, 110);

        lastLabel.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        lastLabel.setForeground(new java.awt.Color(255, 0, 51));
        lastLabel.setText("Congratulations!");
        add(lastLabel);
        lastLabel.setBounds(190, 140, 320, 80);

        backToMainButton.setText("back to main");
        backToMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainButtonActionPerformed(evt);
            }
        });
        add(backToMainButton);
        backToMainButton.setBounds(280, 380, 120, 29);

        lastLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        lastLabel1.setForeground(new java.awt.Color(255, 0, 51));
        lastLabel1.setText("You saved the world!!!!");
        add(lastLabel1);
        lastLabel1.setBounds(130, 180, 470, 140);
    }// </editor-fold>//GEN-END:initComponents

    private void backToMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainButtonActionPerformed
        this.mj.getContentPane().removeAll();
        this.mj.add(this.mj.getMainPanel());
        this.mj.revalidate();
        this.mj.repaint();
    }//GEN-LAST:event_backToMainButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMainButton;
    private javax.swing.JLabel flyingLabel;
    private javax.swing.JLabel lastLabel;
    private javax.swing.JLabel lastLabel1;
    // End of variables declaration//GEN-END:variables
}
