/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package babyKun.scenes;

import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jack
 */
public class GenerateKun extends javax.swing.JPanel {

    /**
     * Creates new form GenerateKun
     */
    public static int score;
    public static String kunName;
    public static String yourName;
    DefaultTableModel model;
    String cKun;
    ArrayList<Integer> arr;
    babyKun.database.DataBase db;
    public mainJFrame mj;

    /**
     * Constructor for GenerateKun.
     *
     * @param mj frame main class mainJFrame to ensure all the panels are on one
     */
    public GenerateKun(mainJFrame mj) {
        this.mj = mj;
        initComponents();
        findAttribute();
        cTable.getColumnModel().setColumnMargin(10);

        //Initilize the value in JTable
        model = (DefaultTableModel) cTable.getModel();
        model.insertRow(model.getRowCount(), new Object[]{kunName, arr.get(0), arr.get(1), arr.get(2), arr.get(3), arr.get(4), arr.get(5) + "%"});
        showC.setText(calculateCharacteristic());

    }

    /**
     * Method to find kun's character based on the score of questions.
     *
     * @return kun's character
     */
    public String calculateCharacteristic() {

        if (score == 3) {
            cKun = "Quiet";
        } else if (score == 4) {
            cKun = "Loyal";
        } else if (score == 5 || score == 6) {
            cKun = "Smart";
        } else if (score == 7) {
            cKun = "Fashionable";
        } else if (score == 8) {
            cKun = "Adorable";
        } else {
            cKun = "Strong";
        }

        return cKun;
    }

    /**
     * Method to get attributed of kun based on the name in database
     */
    public void findAttribute() {

        db = new babyKun.database.DataBase();
        db.createCharacterDB();
        arr = db.CharacterAttributes(calculateCharacteristic());
        Fight.kunAttributes = arr;
    }

    /**
     * Method to find kun's character based on the score of questions.
     *
     * @param number points
     * @return kun's characteristic
     */
    public String calculateC(int number) {

        if (number == 3) {
            cKun = "Quiet";
        } else if (number == 4) {
            cKun = "Loyal";
        } else if (number == 5 || number == 6) {
            cKun = "Smart";
        } else if (number == 7) {
            cKun = "Fashionable";
        } else if (number == 8) {
            cKun = "Adorable";
        } else {
            cKun = "Strong";
        }

        return cKun;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KunGeneratePanel = new javax.swing.JPanel();
        eggLabel = new javax.swing.JLabel();
        content_1 = new javax.swing.JLabel();
        content_2 = new javax.swing.JLabel();
        content_3 = new javax.swing.JLabel();
        dialogLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cTable = new javax.swing.JTable();
        nextButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        showC = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 500));

        KunGeneratePanel.setBackground(new java.awt.Color(0, 0, 0));
        KunGeneratePanel.setLayout(null);

        eggLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/whaleGif.gif"))); // NOI18N
        KunGeneratePanel.add(eggLabel);
        eggLabel.setBounds(140, 150, 220, 180);

        content_1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        content_1.setText("Hi "+yourName+",");
        KunGeneratePanel.add(content_1);
        content_1.setBounds(360, 140, 140, 16);

        content_2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        content_2.setText(kunName+" is ready now!");
        KunGeneratePanel.add(content_2);
        content_2.setBounds(360, 170, 150, 20);

        content_3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        content_3.setText("Let's fight together!");
        KunGeneratePanel.add(content_3);
        content_3.setBounds(360, 190, 140, 20);

        dialogLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/dialog.gif"))); // NOI18N
        KunGeneratePanel.add(dialogLabel);
        dialogLabel.setBounds(320, 110, 210, 130);

        cTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Health", "Mana", "Attack", "Defence", "Luck", "CriticalChance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cTable);

        KunGeneratePanel.add(jScrollPane1);
        jScrollPane1.setBounds(-2, 340, 700, 50);

        nextButton.setText("Next>>");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        KunGeneratePanel.add(nextButton);
        nextButton.setBounds(620, 440, 94, 29);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your kun's characteristic is:");
        jLabel1.setToolTipText("");
        KunGeneratePanel.add(jLabel1);
        jLabel1.setBounds(30, 90, 190, 30);

        showC.setBackground(new java.awt.Color(0, 0, 0));
        showC.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        showC.setForeground(new java.awt.Color(255, 0, 0));
        KunGeneratePanel.add(showC);
        showC.setBounds(220, 80, 150, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KunGeneratePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KunGeneratePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        JPanel sOne = new SceneOne(this.mj);
        this.mj.getContentPane().removeAll();
        this.mj.add(sOne);
        this.mj.revalidate();
        this.mj.repaint();
    }//GEN-LAST:event_nextButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel KunGeneratePanel;
    private javax.swing.JTable cTable;
    private javax.swing.JLabel content_1;
    private javax.swing.JLabel content_2;
    private javax.swing.JLabel content_3;
    private javax.swing.JLabel dialogLabel;
    private javax.swing.JLabel eggLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel showC;
    // End of variables declaration//GEN-END:variables
}
