/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package babyKun.scenes;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jack
 */
public class PreStart extends javax.swing.JPanel {

    /**
     * Define instances.
     */
    public mainJFrame mj;
    public ArrayList<String> arr;
    public babyKun.database.DataBase db;
    public boolean ifCorrectName = false;

    /**
     * Constructor for PreStart
     *
     * @param frame frame main class mainJFrame to ensure all the panels are on
     * one JFrame
     */
    public PreStart(mainJFrame frame) {
        this.setVisible(true);
        this.mj = frame;
        initComponents();
        db = new babyKun.database.DataBase();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        randomButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        nameLabel.setBackground(new java.awt.Color(255, 255, 255));
        nameLabel.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Please enter or roll your name: ");
        add(nameLabel);
        nameLabel.setBounds(220, 150, 270, 17);

        randomButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/dice.png"))); // NOI18N
        randomButton.setBorderPainted(false);
        randomButton.setContentAreaFilled(false);
        randomButton.setFocusPainted(false);
        randomButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                randomButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                randomButtonMouseEntered(evt);
            }
        });
        randomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomButtonActionPerformed(evt);
            }
        });
        add(randomButton);
        randomButton.setBounds(410, 180, 60, 60);

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        add(nameTextField);
        nameTextField.setBounds(220, 190, 220, 40);

        confirmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/castle.png"))); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmButtonMouseEntered(evt);
            }
        });
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        add(confirmButton);
        confirmButton.setBounds(270, 250, 130, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed

        //Get the name input from the user and assign to relevant classes.
        try {

            if (nameTextField.getText().matches(".*\\d.*") || nameTextField.getText().trim().length() == 0) {
                throw new Exception();
            } else {
                int yesNo = JOptionPane.showConfirmDialog(null, "Are you happy with the name?", "Please confirm", JOptionPane.YES_NO_OPTION);
                if (yesNo == 0) {

                    JPanel story = new Story(this.mj);

                    Questions.userName = nameTextField.getText();
                    GenerateKun.yourName = nameTextField.getText();
                    VIP.name = nameTextField.getText();
                    this.mj.getContentPane().removeAll();
                    this.mj.add(story);
                    this.mj.revalidate();
                    this.mj.repaint();
                }
            }
        } catch (Exception ex) {
            nameTextField.setText("");
            JOptionPane.showMessageDialog(null, "Please enter your correct name",
                    "Letters only plz", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_confirmButtonActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed

    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void randomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomButtonActionPerformed
        //Get random name from database
        Random rd = new Random();
        db.createNameTable();
        arr = db.RandomName();
        int index = rd.nextInt(7);
        nameTextField.setText(arr.get(index));
    }//GEN-LAST:event_randomButtonActionPerformed

    private void randomButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_randomButtonMouseEntered
        //mouse effect
        randomButton.setSize(63, 61);
    }//GEN-LAST:event_randomButtonMouseEntered

    private void randomButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_randomButtonMouseExited
        //mouse effect
        randomButton.setSize(60, 60);
    }//GEN-LAST:event_randomButtonMouseExited

    private void confirmButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMouseEntered
        //mouse effect
        confirmButton.setSize(132, 41);
    }//GEN-LAST:event_confirmButtonMouseEntered

    private void confirmButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMouseExited
        //mouse effect
        confirmButton.setSize(130, 40);
    }//GEN-LAST:event_confirmButtonMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton randomButton;
    // End of variables declaration//GEN-END:variables
}
