/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package babyKun.scenes;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Jack
 */
public class SceneZero extends javax.swing.JPanel {

    //define instances
    public mainJFrame mj;
    int chapterZeroX;
    int chapterZeroY;
    Timer chapterZero_1;
    int chapterZeroX_2;
    int chapterZeroY_2;
    Timer chapterZero_2;

    /**
     * Constructor for SceneZero;
     *
     * @param frame frame main class mainJFrame to ensure all the panels are on
     * one JFrame
     */
    public SceneZero(mainJFrame frame) {
        this.mj = frame;
        initComponents();
        this.nextButton.setVisible(false);
        movingSubtitle();
        movingWhaleOne();

    }

    /**
     * Action of moving words
     */
    public void movingSubtitle() {

        chapterZeroX = chapterZero.getLocation().x;
        chapterZeroY = chapterZero.getLocation().y;

        ActionListener flyingWord = new ActionListener() {
            public void actionPerformed(ActionEvent event) {

                if (chapterZeroX >= 490) {
                    chapterZeroX -= 20;
                    chapterZero.setLocation(chapterZeroX, chapterZeroY);
                } else {
                    chapterZero_1.stop();
                    nextButton.setVisible(true);
                }

            }
        };

        chapterZero_1 = new Timer(70, flyingWord);
        chapterZero_1.start();
    }

    //clear current panel and add Question Panel.
    public void goToQuestions() {
        JPanel sQuestions = new Questions(this.mj);
        this.mj.getContentPane().removeAll();
        this.mj.add(sQuestions);
        this.mj.revalidate();
        this.mj.repaint();
    }

    //Action of moving background pic
    public void movingWhaleOne() {

        chapterZeroX_2 = lastPic.getLocation().x;
        chapterZeroY_2 = lastPic.getLocation().y;

        ActionListener flyingPic = new ActionListener() {
            public void actionPerformed(ActionEvent event) {

                if (chapterZeroX_2 <= 0) {
                    chapterZeroX_2 += 1;
                    lastPic.setLocation(chapterZeroX_2, chapterZeroY_2);
                } else {
                    chapterZero_2.stop();

                }

            }
        };

        chapterZero_2 = new Timer(70, flyingPic);
        chapterZero_2.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chapterZero = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        lastPic = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        chapterZero.setFont(new java.awt.Font("Meiryo", 1, 18)); // NOI18N
        chapterZero.setForeground(new java.awt.Color(51, 51, 51));
        chapterZero.setText("Chapter Zero - End");
        add(chapterZero);
        chapterZero.setBounds(620, 270, 180, 40);

        nextButton.setForeground(new java.awt.Color(102, 102, 102));
        nextButton.setText("Next>>");
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextButtonMouseExited(evt);
            }
        });
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        add(nextButton);
        nextButton.setBounds(620, 320, 80, 25);

        lastPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/whaleOne.png"))); // NOI18N
        add(lastPic);
        lastPic.setBounds(-10, 0, 720, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseEntered
        nextButton.setSize(78, 26);
    }//GEN-LAST:event_nextButtonMouseEntered

    private void nextButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseExited
        nextButton.setSize(75, 25);
    }//GEN-LAST:event_nextButtonMouseExited

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        goToQuestions();
    }//GEN-LAST:event_nextButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chapterZero;
    private javax.swing.JLabel lastPic;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
}
