/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package babyKun.scenes;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jack
 */
public class Shop extends javax.swing.JPanel {

    /**
     * Define instances
     */
    mainJFrame mj;
    public static boolean ifDiscount = false;
    static int healthAmounts;
    static int manaAmounts;
    static int singAmounts;
    static int jumpAmounts;
    static int rapAmounts;
    static int basketBallAmounts;
    double discount = 0.2;
    public static ArrayList<Integer> arr;

    /**
     * Constructor for Shop
     *
     * @param mj frame main class mainJFrame to ensure all the panels are on one
     * JFrame
     */
    public Shop(mainJFrame mj) {
        this.mj = mj;
        initComponents();
        healthAmounts = 100;
        manaAmounts = 50;
        singAmounts = 1000;
        jumpAmounts = 1000;
        rapAmounts = 1500;
        basketBallAmounts = 1000;
        afterDiscount();

    }

    /**
     * Update price if use gets discount
     */
    public void afterDiscount() {
        if (ifDiscount) {
            HealthAmount.setText("$" + Double.toString(healthAmounts * (1 - discount)) + " -- was $" + healthAmounts);
            manaAmount.setText("$" + Double.toString(manaAmounts * (1 - discount)) + " -- was $" + manaAmounts);
            singAmount.setText("$" + Double.toString(singAmounts * (1 - discount)) + " -- was $" + singAmounts);
            jumpAmount.setText("$" + Double.toString(jumpAmounts * (1 - discount)) + " -- was $" + jumpAmounts);
            rapAmount.setText("$" + Double.toString(rapAmounts * (1 - discount)) + " -- was $" + rapAmounts);
            basketBallAmount.setText("$" + Double.toString(basketBallAmounts * (1 - discount)) + " -- was $" + basketBallAmounts);

            healthAmounts *= (1 - discount);
            manaAmounts *= (1 - discount);
            singAmounts *= (1 - discount);
            jumpAmounts *= (1 - discount);
            rapAmounts *= (1 - discount);
            basketBallAmounts *= (1 - discount);

        }
    }

    //calculate after discount price
    public double afterDiscount(double p, double d) {

        double discount = p * (1 - d);
        return discount;
    }

    //remove current Panel, add Map Panel.
    public void goToMap() {
        JPanel map = new Map(this.mj);
        this.mj.getContentPane().removeAll();
        this.mj.add(map);
        this.mj.revalidate();
        this.mj.repaint();
    }

    //remove current Panel, add Basket Panel.
    public void goToBasket() {
        JPanel Basket = new Basket(this.mj);
        this.mj.getContentPane().removeAll();
        this.mj.add(Basket);
        this.mj.revalidate();
        this.mj.repaint();
    }

    /*
    *assign the list to Basket class
     */
    public void addToList(int price, String itemName) {

        Basket.listModel.addElement("@ $" + Integer.toString(price) + "/1* " + itemName);

        JOptionPane.showMessageDialog(null, itemName + ", $" + Integer.toString(price) + " has been added!",
                "Thank you!", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        mainPanel = new javax.swing.JPanel();
        salesLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        vipButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        healthPanel = new javax.swing.JPanel();
        healthLabel1 = new javax.swing.JLabel();
        healthTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        healthPotion = new javax.swing.JTextArea();
        healthGold = new javax.swing.JLabel();
        HealthAmount = new javax.swing.JLabel();
        healthAdd = new javax.swing.JButton();
        manaPanel = new javax.swing.JPanel();
        manaLabel = new javax.swing.JLabel();
        manaTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        manaText = new javax.swing.JTextArea();
        manaGold = new javax.swing.JLabel();
        manaAmount = new javax.swing.JLabel();
        manaAdd = new javax.swing.JButton();
        singPanel = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        singText = new javax.swing.JTextArea();
        healthLabel11 = new javax.swing.JLabel();
        singTitle = new javax.swing.JLabel();
        singGold = new javax.swing.JLabel();
        singAmount = new javax.swing.JLabel();
        singAdd = new javax.swing.JButton();
        jumpPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jumpText = new javax.swing.JTextArea();
        jumpPic = new javax.swing.JLabel();
        jumpTitle = new javax.swing.JLabel();
        jumpGold = new javax.swing.JLabel();
        jumpAmount = new javax.swing.JLabel();
        jumpAdd = new javax.swing.JButton();
        rapPanel = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        rapText = new javax.swing.JTextArea();
        rapPic = new javax.swing.JLabel();
        rapTitle = new javax.swing.JLabel();
        rapGold = new javax.swing.JLabel();
        rapAmount = new javax.swing.JLabel();
        rapAdd = new javax.swing.JButton();
        basketBall = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        basketBallText = new javax.swing.JTextArea();
        basketBallTitle = new javax.swing.JLabel();
        basketBallPic = new javax.swing.JLabel();
        basketBallGolde = new javax.swing.JLabel();
        basketBallAmount = new javax.swing.JLabel();
        basketballAdd = new javax.swing.JButton();
        viewCart = new javax.swing.JButton();
        backToMap = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setLayout(null);

        mainPanel.setLayout(null);

        salesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/sale.png"))); // NOI18N
        mainPanel.add(salesLabel);
        salesLabel.setBounds(370, 0, 150, 150);

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Apply for VIP, and enjoy 20% off!");
        mainPanel.add(jLabel1);
        jLabel1.setBounds(140, 270, 270, 20);

        vipButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/moneybag.png"))); // NOI18N
        vipButton.setText("Apply now");
        vipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vipButtonActionPerformed(evt);
            }
        });
        mainPanel.add(vipButton);
        vipButton.setBounds(180, 300, 143, 40);

        jLabel2.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jLabel2.setText("About us");
        mainPanel.add(jLabel2);
        jLabel2.setBounds(170, 50, 170, 30);

        jLabel3.setFont(new java.awt.Font("Menlo", 0, 15)); // NOI18N
        jLabel3.setText("On of the best shops in Kun's world, ");
        mainPanel.add(jLabel3);
        jLabel3.setBounds(50, 100, 350, 20);

        jLabel4.setFont(new java.awt.Font("Menlo", 0, 15)); // NOI18N
        jLabel4.setText("part of customers' feedback as below -");
        mainPanel.add(jLabel4);
        jLabel4.setBounds(50, 120, 400, 20);

        jLabel5.setText("\"Please, please!! You will never forget this fantasic place!\" -- Harry Potter");
        mainPanel.add(jLabel5);
        jLabel5.setBounds(50, 190, 530, 20);

        jLabel6.setText("\"The staff inside was so fabulous and enthusiastic!\" -- Morgana Hex");
        mainPanel.add(jLabel6);
        jLabel6.setBounds(50, 220, 490, 16);

        jTabbedPane1.addTab("Main", mainPanel);

        healthPanel.setLayout(null);

        healthLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/healthPotion_big.png"))); // NOI18N
        healthPanel.add(healthLabel1);
        healthLabel1.setBounds(60, 120, 149, 159);

        healthTitle.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        healthTitle.setText("Health Potion");
        healthPanel.add(healthTitle);
        healthTitle.setBounds(240, 40, 240, 48);

        healthPotion.setEditable(false);
        healthPotion.setColumns(20);
        healthPotion.setRows(5);
        healthPotion.setText("Attributes:\n\nYear of manufacture: Year 1986\n\nRecover: 100 HP\n");
        healthPotion.setOpaque(false);
        jScrollPane1.setViewportView(healthPotion);

        healthPanel.add(jScrollPane1);
        jScrollPane1.setBounds(240, 100, 240, 120);

        healthGold.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        healthGold.setText("GOLD:");
        healthPanel.add(healthGold);
        healthGold.setBounds(250, 250, 44, 19);

        HealthAmount.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        HealthAmount.setForeground(new java.awt.Color(255, 153, 0));
        HealthAmount.setText("$100");
        healthPanel.add(HealthAmount);
        HealthAmount.setBounds(310, 250, 160, 17);

        healthAdd.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        healthAdd.setText("Add to cart");
        healthAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthAddActionPerformed(evt);
            }
        });
        healthPanel.add(healthAdd);
        healthAdd.setBounds(270, 289, 110, 30);

        jTabbedPane1.addTab("Health Potion", healthPanel);

        manaPanel.setLayout(null);

        manaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/manapotionBig.png"))); // NOI18N
        manaPanel.add(manaLabel);
        manaLabel.setBounds(60, 120, 149, 159);

        manaTitle.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        manaTitle.setText("Mana Potion");
        manaPanel.add(manaTitle);
        manaTitle.setBounds(240, 40, 240, 48);

        manaText.setEditable(false);
        manaText.setColumns(20);
        manaText.setRows(5);
        manaText.setText("Attributes:\n\n\nYear of manufacture: Year 1986\n\nRecover: 50 HP\n\n");
        manaText.setOpaque(false);
        jScrollPane2.setViewportView(manaText);

        manaPanel.add(jScrollPane2);
        jScrollPane2.setBounds(240, 100, 240, 130);

        manaGold.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        manaGold.setText("GOLD:");
        manaPanel.add(manaGold);
        manaGold.setBounds(250, 250, 50, 19);

        manaAmount.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        manaAmount.setForeground(new java.awt.Color(255, 153, 0));
        manaAmount.setText("$50");
        manaPanel.add(manaAmount);
        manaAmount.setBounds(310, 250, 160, 17);

        manaAdd.setText("Add to cart");
        manaAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manaAddActionPerformed(evt);
            }
        });
        manaPanel.add(manaAdd);
        manaAdd.setBounds(270, 290, 95, 25);

        jTabbedPane1.addTab("Mana Potion", manaPanel);

        singPanel.setLayout(null);

        singText.setEditable(false);
        singText.setColumns(20);
        singText.setRows(5);
        singText.setText("Attributes:\n\nYear of priactice: 2.5 years\n\nEffect: Ability added - Sing\n\n(Noice caused 150 damage to \nall the enemies)\n\n");
        singText.setOpaque(false);
        jScrollPane11.setViewportView(singText);

        singPanel.add(jScrollPane11);
        jScrollPane11.setBounds(240, 100, 240, 140);

        healthLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/microphoneBig.png"))); // NOI18N
        singPanel.add(healthLabel11);
        healthLabel11.setBounds(60, 120, 149, 159);

        singTitle.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        singTitle.setText("Sing");
        singPanel.add(singTitle);
        singTitle.setBounds(320, 30, 60, 60);

        singGold.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        singGold.setText("GOLD:");
        singPanel.add(singGold);
        singGold.setBounds(250, 250, 60, 19);

        singAmount.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        singAmount.setForeground(new java.awt.Color(255, 153, 0));
        singAmount.setText("$1000");
        singPanel.add(singAmount);
        singAmount.setBounds(310, 250, 160, 17);

        singAdd.setText("Add to cart");
        singAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singAddActionPerformed(evt);
            }
        });
        singPanel.add(singAdd);
        singAdd.setBounds(270, 290, 95, 25);

        jTabbedPane1.addTab("Sing", singPanel);

        jumpPanel.setLayout(null);

        jumpText.setEditable(false);
        jumpText.setColumns(20);
        jumpText.setRows(5);
        jumpText.setText("Attributes:\n\nYear of manufacture: Year 2004\n\nEffect: Ability added - Jump\n\n(Possible to dodge enemies' attack)\n\n");
        jumpText.setOpaque(false);
        jScrollPane4.setViewportView(jumpText);

        jumpPanel.add(jScrollPane4);
        jScrollPane4.setBounds(240, 100, 240, 130);

        jumpPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/shoeBig.png"))); // NOI18N
        jumpPanel.add(jumpPic);
        jumpPic.setBounds(60, 120, 149, 159);

        jumpTitle.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jumpTitle.setText("Jump");
        jumpPanel.add(jumpTitle);
        jumpTitle.setBounds(330, 40, 70, 48);

        jumpGold.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jumpGold.setText("GOLD:");
        jumpPanel.add(jumpGold);
        jumpGold.setBounds(250, 250, 50, 19);

        jumpAmount.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jumpAmount.setForeground(new java.awt.Color(255, 153, 0));
        jumpAmount.setText("$1000");
        jumpPanel.add(jumpAmount);
        jumpAmount.setBounds(310, 250, 160, 17);

        jumpAdd.setText("Add to cart");
        jumpAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumpAddActionPerformed(evt);
            }
        });
        jumpPanel.add(jumpAdd);
        jumpAdd.setBounds(270, 290, 95, 25);

        jTabbedPane1.addTab("Jump", jumpPanel);

        rapPanel.setLayout(null);

        rapText.setEditable(false);
        rapText.setColumns(20);
        rapText.setRows(5);
        rapText.setText("Attributes:\n\nYear of manufacture: Year 1986\n\nEffect: Ability added - Rap\n\n(LifeSteal with 20% of attack damage)");
        rapText.setOpaque(false);
        jScrollPane12.setViewportView(rapText);

        rapPanel.add(jScrollPane12);
        jScrollPane12.setBounds(240, 110, 240, 130);

        rapPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/rapperBig.png"))); // NOI18N
        rapPanel.add(rapPic);
        rapPic.setBounds(60, 120, 149, 159);

        rapTitle.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        rapTitle.setText("Rap");
        rapPanel.add(rapTitle);
        rapTitle.setBounds(340, 40, 60, 48);

        rapGold.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rapGold.setText("GOLD:");
        rapPanel.add(rapGold);
        rapGold.setBounds(250, 250, 50, 19);

        rapAmount.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        rapAmount.setForeground(new java.awt.Color(255, 153, 0));
        rapAmount.setText("$1500");
        rapPanel.add(rapAmount);
        rapAmount.setBounds(310, 250, 170, 17);

        rapAdd.setText("Add to cart");
        rapAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapAddActionPerformed(evt);
            }
        });
        rapPanel.add(rapAdd);
        rapAdd.setBounds(270, 290, 95, 25);

        jTabbedPane1.addTab("Rap", rapPanel);

        basketBall.setLayout(null);

        basketBallText.setEditable(false);
        basketBallText.setColumns(20);
        basketBallText.setRows(5);
        basketBallText.setText("Attributes:\n\nYear of manufacture: Year 1986\n\nEffect: Ability added - BasketBall\n\n(Possible to stun enemies \nwith basic attack)\n");
        basketBallText.setOpaque(false);
        jScrollPane3.setViewportView(basketBallText);

        basketBall.add(jScrollPane3);
        jScrollPane3.setBounds(240, 110, 240, 130);

        basketBallTitle.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        basketBallTitle.setText("BasketBall");
        basketBall.add(basketBallTitle);
        basketBallTitle.setBounds(280, 50, 150, 48);

        basketBallPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/basketballBig.png"))); // NOI18N
        basketBall.add(basketBallPic);
        basketBallPic.setBounds(60, 120, 149, 159);

        basketBallGolde.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        basketBallGolde.setText("GOLD:");
        basketBall.add(basketBallGolde);
        basketBallGolde.setBounds(250, 250, 50, 19);

        basketBallAmount.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        basketBallAmount.setForeground(new java.awt.Color(255, 153, 0));
        basketBallAmount.setText("$1000");
        basketBall.add(basketBallAmount);
        basketBallAmount.setBounds(310, 250, 170, 17);

        basketballAdd.setText("Add to cart");
        basketballAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basketballAddActionPerformed(evt);
            }
        });
        basketBall.add(basketballAdd);
        basketballAdd.setBounds(270, 290, 95, 25);

        jTabbedPane1.addTab("BasketBall", basketBall);

        add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 60, 520, 410);

        viewCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/letter.png"))); // NOI18N
        viewCart.setText("View Cart");
        viewCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCartActionPerformed(evt);
            }
        });
        add(viewCart);
        viewCart.setBounds(550, 340, 150, 50);

        backToMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/castle.png"))); // NOI18N
        backToMap.setText("Back");
        backToMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMapActionPerformed(evt);
            }
        });
        add(backToMap);
        backToMap.setBounds(550, 420, 150, 50);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/background.png"))); // NOI18N
        add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 710, 541);
    }// </editor-fold>//GEN-END:initComponents

    private void vipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vipButtonActionPerformed
        //go to VIP Panel if wants to be VIP.   
        if (ifDiscount) {

            JOptionPane.showMessageDialog(null, "You have 20% discount now!");
            vipButton.setEnabled(false);
        } else {
            JPanel vip = new VIP(this.mj);
            this.mj.getContentPane().removeAll();
            this.mj.add(vip);
            this.mj.revalidate();
            this.mj.repaint();
        }
    }//GEN-LAST:event_vipButtonActionPerformed

    private void healthAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthAddActionPerformed
        addToList(healthAmounts, "Health Potion");

    }//GEN-LAST:event_healthAddActionPerformed

    private void manaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manaAddActionPerformed
        addToList(manaAmounts, "Mana Potion");

    }//GEN-LAST:event_manaAddActionPerformed

    private void singAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singAddActionPerformed
        addToList(singAmounts, "Sing skill book");
    }//GEN-LAST:event_singAddActionPerformed

    private void jumpAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumpAddActionPerformed
        addToList(jumpAmounts, "jump skill book");
    }//GEN-LAST:event_jumpAddActionPerformed

    private void rapAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rapAddActionPerformed
        addToList(rapAmounts, "Rap skill book");
    }//GEN-LAST:event_rapAddActionPerformed

    private void basketballAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basketballAddActionPerformed
        addToList(basketBallAmounts, "Basketball skill book");
    }//GEN-LAST:event_basketballAddActionPerformed

    private void backToMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMapActionPerformed
        goToMap();
    }//GEN-LAST:event_backToMapActionPerformed

    private void viewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCartActionPerformed
        goToBasket();
    }//GEN-LAST:event_viewCartActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HealthAmount;
    private javax.swing.JButton backToMap;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel basketBall;
    private javax.swing.JLabel basketBallAmount;
    private javax.swing.JLabel basketBallGolde;
    private javax.swing.JLabel basketBallPic;
    private javax.swing.JTextArea basketBallText;
    private javax.swing.JLabel basketBallTitle;
    private javax.swing.JButton basketballAdd;
    private javax.swing.JButton healthAdd;
    private javax.swing.JLabel healthGold;
    private javax.swing.JLabel healthLabel1;
    private javax.swing.JLabel healthLabel11;
    private javax.swing.JPanel healthPanel;
    private javax.swing.JTextArea healthPotion;
    private javax.swing.JLabel healthTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jumpAdd;
    private javax.swing.JLabel jumpAmount;
    private javax.swing.JLabel jumpGold;
    private javax.swing.JPanel jumpPanel;
    private javax.swing.JLabel jumpPic;
    private javax.swing.JTextArea jumpText;
    private javax.swing.JLabel jumpTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton manaAdd;
    private javax.swing.JLabel manaAmount;
    private javax.swing.JLabel manaGold;
    private javax.swing.JLabel manaLabel;
    private javax.swing.JPanel manaPanel;
    private javax.swing.JTextArea manaText;
    private javax.swing.JLabel manaTitle;
    private javax.swing.JButton rapAdd;
    private javax.swing.JLabel rapAmount;
    private javax.swing.JLabel rapGold;
    private javax.swing.JPanel rapPanel;
    private javax.swing.JLabel rapPic;
    private javax.swing.JTextArea rapText;
    private javax.swing.JLabel rapTitle;
    private javax.swing.JLabel salesLabel;
    private javax.swing.JButton singAdd;
    private javax.swing.JLabel singAmount;
    private javax.swing.JLabel singGold;
    private javax.swing.JPanel singPanel;
    private javax.swing.JTextArea singText;
    private javax.swing.JLabel singTitle;
    private javax.swing.JButton viewCart;
    private javax.swing.JButton vipButton;
    // End of variables declaration//GEN-END:variables
}
