/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package babyKun.scenes;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.Timer;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author Jack
 */
public class Story extends javax.swing.JPanel {

    /**
     * Define instances
     */
    public mainJFrame mj;
    int picMovingSpeed = 4;
    int wordMovingSpeed = 1;
    Timer tm;
    int velx;
    int vely;
    int counter;
    Timer tmW;
    String content;

    /**
     * Constructor for Story
     *
     * @param frame frame main class mainJFrame to ensure all the panels are on
     * one JFrame
     */
    public Story(mainJFrame frame) {

        this.setVisible(true);

        this.mj = frame;
        initComponents();
        movingPic();

        //initize the whole story
        content
                = "Thousands of years ago, in a beautiful planet. \n"
                + "People had a pleasant life with peace and happiness. \n\n"
                + "However, one day, the doom came... \n"
                + "An evil dragon burned the village, slaughtered innocent people. \n\n"
                + "A girl named ‘Kun’, whose parent were both killed by the evil, \n"
                + "decided to sacrifice herself and save others. \n\n"
                + "That battle was lasting for a whole day! \n"
                + "Although Kun finally won the fight, \n"
                + "her energies spreaded into different corners... \n\n"
                + "However, all the people still believe that one day, \n"
                + "Kun would go back to the world and fight with the awaking dragon again! \n";

        DefaultCaret caret = (DefaultCaret) textArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        movingWords(textArea, content);
    }

    //Action of moving story pic
    public void movingPic() {

        velx = movingPic.getLocation().x;
        vely = movingPic.getLocation().y;

        ActionListener flyingPic = new ActionListener() {
            public void actionPerformed(ActionEvent event) {

                if (velx > -1880) {
                    velx -= picMovingSpeed;
                    movingPic.setLocation(velx, vely);
                } else {
                    tm.stop();

                }

            }
        };

        tm = new Timer(60, flyingPic);
        tm.start();

    }

    //Story appears in JTextarea with chars pop up one by one
    public void movingWords(final JTextArea area, final String text) {

        ActionListener flyingWord = new ActionListener() {
            public void actionPerformed(ActionEvent event) {

                counter += wordMovingSpeed;
                if (counter > text.length()) {

                    tm.stop();

                } else {
                    area.setText(text.substring(0, counter));

                }

            }
        };

        tmW = new Timer(80, flyingWord);
        tmW.start();
    }

    //clear current panel and add SceneZero panel
    public void goToSceneZero() {
        JPanel sZero = new SceneZero(this.mj);
        this.mj.getContentPane().removeAll();
        this.mj.add(sZero);
        this.mj.revalidate();
        this.mj.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movingPic = new javax.swing.JLabel();
        skipButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        movingPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babyKun/icons/final.png"))); // NOI18N
        add(movingPic);
        movingPic.setBounds(700, 40, 2350, 320);

        skipButton.setBackground(new java.awt.Color(255, 255, 255));
        skipButton.setText("Skip");
        skipButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                skipButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                skipButtonMouseEntered(evt);
            }
        });
        skipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipButtonActionPerformed(evt);
            }
        });
        add(skipButton);
        skipButton.setBounds(620, 460, 70, 30);

        jScrollPane1.setBorder(null);

        textArea.setBackground(new java.awt.Color(0, 0, 0));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        textArea.setForeground(new java.awt.Color(255, 255, 255));
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 410, 680, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void skipButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skipButtonMouseEntered
        skipButton.setSize(73, 31);
    }//GEN-LAST:event_skipButtonMouseEntered

    private void skipButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skipButtonMouseExited
        skipButton.setSize(70, 30);
    }//GEN-LAST:event_skipButtonMouseExited

    private void skipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipButtonActionPerformed

        int yesOrNo = JOptionPane.showConfirmDialog(null, "Are you sure to skip the story?", "Please confirm", JOptionPane.YES_NO_OPTION);

        if (yesOrNo == 0) {
            JPanel sZero = new SceneZero(this.mj);
            goToSceneZero();
        }
    }//GEN-LAST:event_skipButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel movingPic;
    private javax.swing.JButton skipButton;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
